[tool.poetry.scripts]
flow = 'gtnhvelo.cli:main'

[tool.poetry]
name = "gtnhvelo"
version = "0.1.2"
description = "Factory Optimization Flowcharts for Gregtech: New Horizons"
authors = ["velolib <vlocitize@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
graphviz = "^0.20.1"
pyreadline3 = "^3.4.1"
PyYAML = "^6.0"
rich = "^13.0.0"
sympy = "^1.11.1"
typer = "^0.7.0"
getchlib = "^1.0.12"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
