[project]
name = 'gtnhvelo'
description = 'Factory Optimization Flowcharts for Gregtech: New Horizons'
requires-python = '>=3.10'
readme = 'README.md'
version = '0.1.2'
authors = [
    { name = 'velo', email = 'vlocitize@gmail.com' }
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',

]
dependencies = [
    'graphviz>=0.20.1',
    'pyreadline3>=3.4.1',
    'PyYAML>=6.0',
    'requests>=2.28.1',
    'rich>=13.0.0',
    'sympy>=1.11.1',
    'typer>=0.7.0',
]

[build-system]
build-backend = 'flit_core.buildapi'
requires = ['flit_core >=3.2,<4']

[project.scripts]
flow = 'gtnhvelo.cli:main'

[project.optional-dependencies]
tests = [
    'pytest>=7.2.0',
]